// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.3
// source: proto/membership/membership.proto

package membership

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heartbeat     int32                  `protobuf:"varint,1,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Incarnation   int32                  `protobuf:"varint,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_proto_membership_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{0}
}

func (x *NodeState) GetHeartbeat() int32 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *NodeState) GetIncarnation() int32 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *NodeState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GossipPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Membership    map[string]*NodeState  `protobuf:"bytes,1,rep,name=membership,proto3" json:"membership,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipPushRequest) Reset() {
	*x = GossipPushRequest{}
	mi := &file_proto_membership_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipPushRequest) ProtoMessage() {}

func (x *GossipPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipPushRequest.ProtoReflect.Descriptor instead.
func (*GossipPushRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{1}
}

func (x *GossipPushRequest) GetMembership() map[string]*NodeState {
	if x != nil {
		return x.Membership
	}
	return nil
}

type GossipPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipPushResponse) Reset() {
	*x = GossipPushResponse{}
	mi := &file_proto_membership_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipPushResponse) ProtoMessage() {}

func (x *GossipPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipPushResponse.ProtoReflect.Descriptor instead.
func (*GossipPushResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{2}
}

type GossipJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipJoinRequest) Reset() {
	*x = GossipJoinRequest{}
	mi := &file_proto_membership_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipJoinRequest) ProtoMessage() {}

func (x *GossipJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipJoinRequest.ProtoReflect.Descriptor instead.
func (*GossipJoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{3}
}

func (x *GossipJoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GossipJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Membership    map[string]*NodeState  `protobuf:"bytes,1,rep,name=membership,proto3" json:"membership,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipJoinResponse) Reset() {
	*x = GossipJoinResponse{}
	mi := &file_proto_membership_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipJoinResponse) ProtoMessage() {}

func (x *GossipJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipJoinResponse.ProtoReflect.Descriptor instead.
func (*GossipJoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{4}
}

func (x *GossipJoinResponse) GetMembership() map[string]*NodeState {
	if x != nil {
		return x.Membership
	}
	return nil
}

var File_proto_membership_membership_proto protoreflect.FileDescriptor

const file_proto_membership_membership_proto_rawDesc = "" +
	"\n" +
	"!proto/membership/membership.proto\x12\n" +
	"membership\"c\n" +
	"\tNodeState\x12\x1c\n" +
	"\theartbeat\x18\x01 \x01(\x05R\theartbeat\x12 \n" +
	"\vincarnation\x18\x02 \x01(\x05R\vincarnation\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xb8\x01\n" +
	"\x11GossipPushRequest\x12M\n" +
	"\n" +
	"membership\x18\x01 \x03(\v2-.membership.GossipPushRequest.MembershipEntryR\n" +
	"membership\x1aT\n" +
	"\x0fMembershipEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.membership.NodeStateR\x05value:\x028\x01\"\x14\n" +
	"\x12GossipPushResponse\",\n" +
	"\x11GossipJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xba\x01\n" +
	"\x12GossipJoinResponse\x12N\n" +
	"\n" +
	"membership\x18\x01 \x03(\v2..membership.GossipJoinResponse.MembershipEntryR\n" +
	"membership\x1aT\n" +
	"\x0fMembershipEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.membership.NodeStateR\x05value:\x028\x012\xad\x01\n" +
	"\x11MembershipService\x12K\n" +
	"\n" +
	"GossipPush\x12\x1d.membership.GossipPushRequest\x1a\x1e.membership.GossipPushResponse\x12K\n" +
	"\n" +
	"GossipJoin\x12\x1d.membership.GossipJoinRequest\x1a\x1e.membership.GossipJoinResponseB\x18Z\x16cs425/proto/membershipb\x06proto3"

var (
	file_proto_membership_membership_proto_rawDescOnce sync.Once
	file_proto_membership_membership_proto_rawDescData []byte
)

func file_proto_membership_membership_proto_rawDescGZIP() []byte {
	file_proto_membership_membership_proto_rawDescOnce.Do(func() {
		file_proto_membership_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_membership_membership_proto_rawDesc), len(file_proto_membership_membership_proto_rawDesc)))
	})
	return file_proto_membership_membership_proto_rawDescData
}

var file_proto_membership_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_membership_membership_proto_goTypes = []any{
	(*NodeState)(nil),          // 0: membership.NodeState
	(*GossipPushRequest)(nil),  // 1: membership.GossipPushRequest
	(*GossipPushResponse)(nil), // 2: membership.GossipPushResponse
	(*GossipJoinRequest)(nil),  // 3: membership.GossipJoinRequest
	(*GossipJoinResponse)(nil), // 4: membership.GossipJoinResponse
	nil,                        // 5: membership.GossipPushRequest.MembershipEntry
	nil,                        // 6: membership.GossipJoinResponse.MembershipEntry
}
var file_proto_membership_membership_proto_depIdxs = []int32{
	5, // 0: membership.GossipPushRequest.membership:type_name -> membership.GossipPushRequest.MembershipEntry
	6, // 1: membership.GossipJoinResponse.membership:type_name -> membership.GossipJoinResponse.MembershipEntry
	0, // 2: membership.GossipPushRequest.MembershipEntry.value:type_name -> membership.NodeState
	0, // 3: membership.GossipJoinResponse.MembershipEntry.value:type_name -> membership.NodeState
	1, // 4: membership.MembershipService.GossipPush:input_type -> membership.GossipPushRequest
	3, // 5: membership.MembershipService.GossipJoin:input_type -> membership.GossipJoinRequest
	2, // 6: membership.MembershipService.GossipPush:output_type -> membership.GossipPushResponse
	4, // 7: membership.MembershipService.GossipJoin:output_type -> membership.GossipJoinResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_membership_membership_proto_init() }
func file_proto_membership_membership_proto_init() {
	if File_proto_membership_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_membership_membership_proto_rawDesc), len(file_proto_membership_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_membership_membership_proto_goTypes,
		DependencyIndexes: file_proto_membership_membership_proto_depIdxs,
		MessageInfos:      file_proto_membership_membership_proto_msgTypes,
	}.Build()
	File_proto_membership_membership_proto = out.File
	file_proto_membership_membership_proto_goTypes = nil
	file_proto_membership_membership_proto_depIdxs = nil
}
